[package]
name = "stream-protocol-lib"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = "0.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["preserve_order"] }
unicode-segmentation = "1.11.0"