use stream_protocol_lib::chunkers::json_growing_tree_chunker::JsonGrowingTreeChunker;

#[test]
fn test_json_chunk_iter() {
    use serde_json::json;

    let json_to_test = [
        (
            json!("abcdefghi"),
            [
                json!("ab"),
                json!("abcd"),
                json!("abcdef"),
                json!("abcdefgh"),
                json!("abcdefghi"),
            ].to_vec()
        ),
        (
            json!("東京都"), // buf_size being 2 bytes, but UTF8 graphemes being more than 2 bytes, we should have one at a time
            [
                json!("東"),
                json!("東京"),
                json!("東京都"),
            ].to_vec()
        ),
        (
            json!(["first","second"]),
            [
                json!([""]),
                json!(["fi"]),
                json!(["firs"]),
                json!(["first"]),
                json!(["first", ""]),
                json!(["first", "se"]),
                json!(["first", "seco"]),
                json!(["first", "second"]),
            ].to_vec()
        ),
        (
            json!({"first": "first", "second":"second"}),
            [
                json!({"first": ""}),
                json!({"first": "fi"}),
                json!({"first": "firs"}),
                json!({"first": "first"}),
                json!({"first": "first", "second": ""}),
                json!({"first": "first", "second": "se"}),
                json!({"first": "first", "second": "seco"}),
                json!({"first": "first", "second": "second"}),
            ].to_vec()
        ),
        (
            json!({"parent": {"first":["some", "array"], "second": 123, "third": true, "fourth": null, "fifth": {"a": "tail"}}}),
            [
                json!({"parent": {}}),
                json!({"parent": {"first": []}}),
                json!({"parent": {"first": [""]}}),
                json!({"parent": {"first": ["so"]}}),
                json!({"parent": {"first": ["some", ""]}}),
                json!({"parent": {"first": ["some", "ar"]}}),
                json!({"parent": {"first": ["some", "arra"]}}),
                json!({"parent": {"first": ["some", "array"], "second": 123}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true, "fourth": null}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true, "fourth": null, "fifth": {}}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true, "fourth": null, "fifth": {"a": ""}}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true, "fourth": null, "fifth": {"a": "ta"}}}),
                json!({"parent": {"first": ["some", "array"], "second": 123, "third": true, "fourth": null, "fifth": {"a": "tail"}}}),
            ].to_vec()
        )
    ];
    for (to_test, result) in json_to_test {
        let chunker = JsonGrowingTreeChunker::new(&to_test);
        let chunk_iter = chunker.chunks(2);
        for (chunk_idx, chunk) in chunk_iter.enumerate() {
            let chunk_value = chunk.borrow();
            assert!(chunk_idx < result.len());
            assert_eq!(*chunk_value, result[chunk_idx]);
        }
    }
}

#[test]
// This is a manual test
fn test_json_multibyte() {
    use serde_json::json;
    let json_to_test = [
        (
            json!({
                "h1":"Kurocoの特徴",
                "introduction":"Kurocoの特徴は以下の通りです。",
                "contents":[
                    {
                        "h2":"複数の会社が同時に開発できる",
                        "paragraph":[
                            {
                                "text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します",
                                "references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}
                            },
                            {
                                "text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します",
                                "references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}
                            }
                        ]
                    },
                    {
                        "h2":"複数の会社が同時に開発できる",
                        "paragraph":[
                            {
                                "text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します",
                                "references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}
                            },
                            {
                                "text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します",
                                "references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}
                            }
                        ]
                    }
                ],
                "conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。",
                "areferencesNote":{
                    "1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},
                    "2":{"url":"https://www.kuroco.app/ja/","note":"日本語版サイト"}
                }
            }),
            [
                r#"{"h1":""}"#,
                r#"{"h1":"Kurocoの"}"#,
                r#"{"h1":"Kurocoの特徴"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":""}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りで"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":""}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発で"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":""}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイム"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグの"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/j"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":""}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面から"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計する"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することに"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスム"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現し"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/j"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":""}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発で"}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":""}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイム"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグの"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/j"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":""}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面から"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計する"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することに"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスム"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現し"}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":""}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuro"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/j"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}]}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":""}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このよ"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKu"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そし"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパー"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナラ"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAP"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファー"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストの"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。"}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":""}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuro"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":""}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":""}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuro"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuroco.app/j"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuroco.app/ja/","note":""}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuroco.app/ja/","note":"日本語"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuroco.app/ja/","note":"日本語版サイ"}}}"#,
                r#"{"h1":"Kurocoの特徴","introduction":"Kurocoの特徴は以下の通りです。","contents":[{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]},{"h2":"複数の会社が同時に開発できる","paragraph":[{"text":"API連携による高速開発が可能で、タイムラグのない開発体験を提供します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}},{"text":"管理画面からAPIを設計することによって、柔軟でスムーズな開発が実現します","references":{"1":"https://www.kuroco.app/","2":"https://www.kuroco.app/ja/"}}]}],"conclusion":"このようにKurocoは、柔軟性、迅速な開発、そしてパーソナライズ機能を持ったAPIファーストのHeadless CMSです。","areferencesNote":{"1":{"url":"https://www.kuroco.app/","note":"英語版サイト"},"2":{"url":"https://www.kuroco.app/ja/","note":"日本語版サイト"}}}"#
            ].to_vec()
        )
    ];

    for (to_test, result) in json_to_test {
        let chunker = JsonGrowingTreeChunker::new(&to_test);
        let chunk_iter = chunker.chunks(8);
        for (_chunk_idx, chunk) in chunk_iter.enumerate() {
            let chunk_value = chunk.borrow();
            assert_eq!(*chunk_value.to_string().as_str(), result[_chunk_idx].to_string());
        }
    }
}